### ISSUE TITLE
4scanner gives "max retries exceeded" error, and yet continues downloading images normally.

### ISSUE THREAD

**Issue by Rich700000000000** [Lacsap-/4scanner#21] opened 2016-04-22 15:25 UTC
Ok, so this is weird.

I had installed 4scanner on my server a few days ago, and I haven't updated it with my commit yet: It's still checking every 10 minutes, not 5. It's still on `4scanner==1.0.7`

However, this is just strange: In the terminal window that I'm running in, 4scanner *appears* to go crazy, and give me endlessly repeating error hundreds of times:

`urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='boards.4chan.org', port=80): Max retries exceeded with url`

And yet, it's *still downloading*: When I check the folder (with `find . -type f | wc -l`) it shows me that more and more imaged keep appearing. It's still working fine.

How can it give me hundreds of error and yet still be working fine? What could be going on here?

**Comment by Lacsap-** [comment] 2016-04-22 15:39
My guess is that 4scanner is downloading too much pictures at the same time and 4chan is actively blocking some of your images download.

Since I made a try catch around the image download to prevent 4scanner from crashing if the requested image is unavailable, you keep getting the error but 4scanner do not crash.

The problem is every time you get this error a picture is not downloaded since 4chan blocks your connection.

Maybe I could put a delay between each image download, this way 4scanner would spam 4chan less and hopefully it will stop blocking the downloads.

image download code for reference:
```
                        try:
                            urllib.request.urlretrieve('http:' + link, directory + img)
                        except urllib.error.HTTPError as err:
                            pass
```

**Comment by Rich700000000000** [comment] 2016-04-22 15:42
Ok. And actually, I think it might have something to do with requests, because I got this too:

    Traceback (most recent call last):
      File "/usr/local/bin/4scanner", line 38, in <module>
        main()
      File "/usr/local/bin/4scanner", line 33, in main
        scanner.scan(args.keywords_file, output, log_file)
      File "/usr/local/lib/python3.4/dist-packages/scanner/scanner.py", line 82, in scan
        except requests.exceptions.HTTPError as err:
    NameError: name 'requests' is not defined

**Comment by Lacsap-** [comment] 2016-04-22 16:00
hmm I might be catching the wrong error here. That would explain why it's throwing the error you posted instead of printing:

```print("Error while opening {0} catalog page. "
                      "Retrying during next scan.".format(board))```

Thanks for the info! I'll try to fix it during the weekend.

**Comment by Rich700000000000** [comment] 2016-04-22 16:11
No problem.

**Comment by Lacsap-** [comment] 2016-04-23 01:28
Both errors should hopefully be fixed in 4scanner 1.1.0 ! (upgrade with pip3)

**Comment by Rich700000000000** [comment] 2016-04-23 04:14
That's awesome, thank you.

**Comment by Rich700000000000** [comment] 2016-04-23 04:33
What did you do, it's way faster now.

**Comment by Lacsap-** [comment] 2016-04-23 13:29
I guess it's a side effect of remaking all the download code, instead of scraping the thread html for pictures to download I use the json API now. (```http://a.4cdn.org/{board}/thread/{thread number}.json```)

**Comment by Lacsap-** [comment] 2016-04-25 16:40
Did the error happen again? If not can we close the issue?

**Comment by Rich700000000000** [comment] 2016-04-25 23:29
Well, I did get a *few* `404 json not found` errors, but those should be simple to handle.

**Comment by Lacsap-** [comment] 2016-04-25 23:55
hmm, I guess the 2 seconds sleep I put between each pictures download isn't enough to keep 4chan from blocking some api request.. Maybe I'll put an option to wait n seconds for people who are downloading a lot of pictures at the same time.

Ex ```--wait-time 10``` would wait 10 second between each pictures download.

**Closed** 2016-07-11 22:42 UTC
Labels: bug
